# Generated by Django 5.1 on 2024-08-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('job_description', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=20)),
                ('marital_status', models.CharField(max_length=20)),
            ],
        ),
    ]
